 import { useState } from "react";
 import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
 import { Input } from "@/components/ui/input";
 import { Badge } from "@/components/ui/badge";
 import { Switch } from "@/components/ui/switch";
 import { Label } from "@/components/ui/label";
 import { Search } from "lucide-react";
 
 const vocabulary = [
   {
     term: "Channel",
     simple: "A path for water to flow through",
     advanced: "A conduit with an open surface for conveying water"
   },
   {
     term: "Continuity",
     simple: "What goes in must come out",
     advanced: "Mass is conserved; flow entering equals flow exiting (assuming no storage change)"
   },
   {
     term: "Drain",
     simple: "A pipe or channel that carries water away",
     advanced: "Infrastructure designed to convey stormwater from surfaces to treatment or discharge points"
   },
   {
     term: "Evaporation",
     simple: "When water turns into invisible gas and floats up",
     advanced: "The process by which liquid water becomes water vapor due to heat energy"
   },
   {
     term: "Flow Rate",
     simple: "How much water passes by each second",
     advanced: "Volume of water per unit time (e.g., m³/s or L/s)"
   },
   {
     term: "Friction",
     simple: "The rubbing that slows things down",
     advanced: "Resistance to flow caused by surface roughness and fluid viscosity"
   },
   {
     term: "Gravity",
     simple: "The force that pulls everything down",
     advanced: "The fundamental force of attraction; causes water to flow downhill"
   },
   {
     term: "Hydraulic Radius (R)",
     simple: "A number that tells us how 'efficient' a pipe shape is",
     advanced: "Cross-sectional area divided by wetted perimeter; larger R = more efficient flow"
   },
   {
     term: "Manning's n",
     simple: "A number that tells us how bumpy a surface is",
     advanced: "Empirical coefficient representing surface resistance to flow; higher n = more resistance"
   },
   {
     term: "Monsoon",
     simple: "A season with lots and lots of rain",
     advanced: "Seasonal wind pattern that brings heavy precipitation to tropical regions"
   },
   {
     term: "Reservoir",
     simple: "A big lake that stores water",
     advanced: "Natural or artificial water storage facility"
   },
   {
     term: "Runoff",
     simple: "Rain that flows along the ground instead of soaking in",
     advanced: "Precipitation that flows over land surfaces to streams, rivers, or drains"
   },
   {
     term: "Slope",
     simple: "How steep something is (like a hill or slide)",
     advanced: "Change in elevation divided by horizontal distance; expressed as percentage or ratio"
   },
   {
     term: "Stormwater",
     simple: "Rain that needs to be drained away",
     advanced: "Runoff generated by precipitation events that flows into drainage systems"
   },
   {
     term: "St. Venant Equations",
     simple: "The math rules that tell us how water moves",
     advanced: "A system of partial differential equations describing unsteady open-channel flow (continuity + momentum)"
   },
   {
     term: "SWMM",
     simple: "A computer program engineers use to plan drains",
     advanced: "EPA's dynamic rainfall-runoff simulation model for urban drainage systems"
   },
   {
     term: "Velocity",
     simple: "How fast water is moving",
     advanced: "Speed and direction of flow, typically in m/s"
   },
   {
     term: "Water Cycle",
     simple: "Water's endless journey: ocean → clouds → rain → drains → ocean",
     advanced: "The continuous movement of water through evaporation, condensation, precipitation, and runoff"
   }
 ];
 
 export const VocabularyGlossary = () => {
   const [searchTerm, setSearchTerm] = useState("");
   const [showAdvanced, setShowAdvanced] = useState(false);
   
   const filteredVocabulary = vocabulary.filter(item =>
     item.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
     item.simple.toLowerCase().includes(searchTerm.toLowerCase()) ||
     item.advanced.toLowerCase().includes(searchTerm.toLowerCase())
   );
   
   return (
     <Card>
       <CardHeader>
         <CardTitle className="flex items-center gap-2">
           📖 Vocabulary Glossary
         </CardTitle>
         <p className="text-sm text-muted-foreground">
           Key terms explained at different levels
         </p>
       </CardHeader>
       <CardContent className="space-y-4">
         <div className="flex flex-col sm:flex-row gap-4">
           <div className="relative flex-1">
             <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
             <Input
               placeholder="Search terms..."
               value={searchTerm}
               onChange={(e) => setSearchTerm(e.target.value)}
               className="pl-10"
             />
           </div>
           <div className="flex items-center gap-2">
             <Switch
               id="advanced-mode"
               checked={showAdvanced}
               onCheckedChange={setShowAdvanced}
             />
             <Label htmlFor="advanced-mode" className="text-sm">
               Show technical definitions
             </Label>
           </div>
         </div>
         
         <div className="space-y-3 max-h-[500px] overflow-y-auto pr-2">
           {filteredVocabulary.map((item, index) => (
             <div
               key={index}
               className="p-4 border rounded-lg hover:bg-secondary/20 transition-colors"
             >
               <div className="flex items-start justify-between gap-2 mb-2">
                 <h4 className="font-semibold text-foreground">{item.term}</h4>
                 <Badge variant={showAdvanced ? "default" : "secondary"} className="text-xs shrink-0">
                   {showAdvanced ? "Technical" : "Simple"}
                 </Badge>
               </div>
               <p className="text-sm text-muted-foreground">
                 {showAdvanced ? item.advanced : item.simple}
               </p>
               {showAdvanced && (
                 <p className="text-xs text-muted-foreground/70 mt-2 italic">
                   Simple: {item.simple}
                 </p>
               )}
             </div>
           ))}
           
           {filteredVocabulary.length === 0 && (
             <div className="text-center py-8 text-muted-foreground">
               No terms found matching "{searchTerm}"
             </div>
           )}
         </div>
         
         <div className="text-xs text-muted-foreground text-center pt-2">
           {filteredVocabulary.length} of {vocabulary.length} terms shown
         </div>
       </CardContent>
     </Card>
   );
 };